### ISSUE TITLE
ROS tr_hat_bridge Commands Not Working

### ISSUE THREAD

**Issue by hasahmed** [TurtleRover/tr_ros#1]
I'm not sure if this is a setup issue on my end or not so i'll create the issue here in the hopes that you can at least point me in the right direction.

None of the ROS commands or messages to /tr_hat_bridge work.

I have roscore running and I have run `rosrun tr_hat_bridge tr_hat_bridge &` and everything seems to be working fine, but when running `rostopic pub /tr_hat_bridge/motors tr_hat_msgs/MotorPower "[0.5, 0, 0, 0]"` an error is produced "Did not recieve a valid response after motor command"

Similarly running `rosservice call /tr_hat_bridge/get_battery` results in the following output:
```
success: False
battery: 0.0
```

I have followed all of the steps in these tutorials:
https://docs.turtlerover.com/ros-tutorials/install-ros-on-turtle-rover
https://docs.turtlerover.com/ros-tutorials/install-turtle-rover-ros-package
https://docs.turtlerover.com/ros-tutorials/testing-turtle-rover-ros-nodes
including flashing the new firmware to the hat.

I've tested the regular tos (tcs) software on the same rover (simply switched out the sd card), and everything works fine when visiting local turtle control software local site (for me http://192.168.1.3/).

I'm totally at a loss. Any help you can provide would be appreciated.

some system info:
`$uname -srm`
`Linux 4.14.98-v7+ armv7l`

`$ cat /etc/os-release`
```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

`$ roscore`
```
... logging to /home/ubuntu/.ros/log/c90d95fa-92b6-11e9-9d9c-b827ebca9b5a/roslaunch-ubiquityrobot-1300.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubiquityrobot.local:38217/
ros_comm version 1.12.14


SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES

auto-starting new master
process[master]: started with pid [1310]
ROS_MASTER_URI=http://ubiquityrobot.local:11311/

setting /run_id to c90d95fa-92b6-11e9-9d9c-b827ebca9b5a
process[rosout-1]: started with pid [1323]
started core service [/rosout]
```

Thanks again for any help you can give.

**Comment by bjsowa** [comment]
Sorry for the inconvenience. I think I fixed the issue.

Could you try using the newer [firmware](https://github.com/TurtleRover/firmware-shield/releases/download/1.3.3/firmware-shield.elf) version I just released and tr_ros from [development branch](https://github.com/TurtleRover/tr_ros/tree/development) ?

There is a couple of changes in ROS communication. Topics now use standard messages (no tr_hat_msgs package) and services were changed to topics.

So, to read battery voltage, just type:
```
rostopic echo /tr_hat_bridge/battery
```
To test setting motor power:
```
rostopic pub /tr_hat_bridge/motors std_msgs/Float32MultiArray "{data: [0.5, 0, 0, 0]}"
```

I'll update the tutorials when the changes will be merged to `master`

**Comment by hasahmed** [comment]
Thank you. Working now.
